### ISSUE TITLE
flutter_pcm_sound: Play Audio Realtime From Binary Data Stream

### ISSUE THREAD

**Issue by BinhT1** [chipweinberger/flutter_pcm_sound#1]
My mobile app receives binary data stream from server socket and i want to play audio Realtime immediately. If server socket send data in 3 minutes, my mobile app will play audio in 3 minutes too. But the audio depends on sample rate. If sample rate is too high or too low, my mobile app will play audio faster or slower. Faster will get error when the audio cannot feed more data. How can i play audio synchronous with socket server.

Now, my code is like this:

Listen socket and push to queue, 4 first bytes is id so i remove it

    super.initState();
    FlutterPcmSound.setLogLevel(LogLevel.verbose);
    FlutterPcmSound.setup(sampleRate: 8000, channelCount: 1);
    FlutterPcmSound.setFeedThreshold(4000);
    FlutterPcmSound.setFeedCallback(onFeed);

    _streamSubscription =
        WebsocketRepository().streamBinary.listen((binaryMessage) {
      if (binaryMessage?.length == 4) {
      } else {
        binaryQueue.add(binaryMessage.sublist(4));
      }
    });

onFeed function

<pre>
  void onFeed(int remainingFrames) async {    
    setState(() {    
      _remainingFrames = remainingFrames;   
    });   

    if (stopFeeding == false) {
      if (binaryQueue.isNotEmpty) {
        var frames = binaryQueue.removeFirst();
        await FlutterPcmSound.feed(PcmArrayInt16.fromList(frames));
      } else {
        return;
      }
    }
  }
</pre>

**Comment by chipweinberger** [comment]
looks good to me

**Comment by BinhT1** [comment]
oh sorry, my problem is the binary data is NOT PCM format, they are binary raw from mp3 file. how can i convert binary data from mp3 file to PCM format?

**Comment by chipweinberger** [comment]
try asking google

**Comment by oliverbytes** [comment]
Is there a full sample like this?
