### ISSUE TITLE
How to change the volume?

### ISSUE THREAD

**Issue by cool2apps** [chipweinberger/flutter_pcm_sound#14]
Hello,
Is it possible to change the volume of the sound that generated? I found a workaround with another package called volume_controller. But It is not a good solution. Because I need to change the system volume level with this package. And users may not like this method.

**Comment by chipweinberger** [comment]
you cant change system volume.

but you can reduce volume by multiplying all numbers by 0.5x,   etc.

**Comment by cool2apps** [comment]
> you cant change system volume.
> 
> but you can reduce volume by multiplying all numbers by 0.5x, etc.

Second method is better.  Multiplying by will change the volume level linearly? Can I have 10% or 50% volume level by multiplying by 0.1x or 0.5x?

**Comment by cool2apps** [comment]
thanks for help.
