### ISSUE TITLE
AudioUnitError, AudioUnitGetProperty IsRunning failed

### ISSUE THREAD

**Issue by saarikivit** [chipweinberger/flutter_pcm_sound#24]
Exception has occurred.
PlatformException (PlatformException(AudioUnitError, AudioUnitGetProperty IsRunning failed. OSStatus: -50, null, null))

With the new 3.1.0 (thanks for the update btw!) I started getting these errors. Perhaps calling .release() is the real problem here?

Here is the code: The .feed method is the root of the issue.
```dart
  Future<void> _onFeed(int rf) async {
    ArrayInt16 buf16 = ArrayInt16.zeros(numShorts: SynthConfig.bufferSize);
    synth.renderInterleavedInt16(buf16);
    await FlutterPcmSound.feed(PcmArrayInt16(bytes: buf16.bytes));
  }
```

Any thoughts?

Now that there is no start and stop, I wonder how I should operate? 🤔 

I have an app with a synth. When I press play I want to play. And when I press stop I release. Is that correct? But I need to press play again many times in a session, is that an issue?

Best,

**Comment by chipweinberger** [comment]
on master I added a 'start' function, which just invokes your feed callback.  

can you open a PR for this? I have not hit this issue. must be related to release.

**Comment by chipweinberger** [comment]
I think you did not wait for `setup` to finish?

**Comment by chipweinberger** [comment]
should probably work in 3.1.1

**Comment by saarikivit** [comment]
> I think you did not wait for `setup` to finish?
> 
> in my app I just call `setup` once, and never `release`

Ok, I decided to do this. No errors anymore. Just open the audio at start and never release. I guess it's not a problem to hold the audio resources forever. 🤷

I'll just close this one. Thanks!
