### ISSUE TITLE
How to pause?

### ISSUE THREAD

**Issue by gokturkDev** [chipweinberger/flutter_pcm_sound#27]
Older version (1) had a pause function.
`FlutterPcmSound.pause()`
I can't seem to find a similar method in v3.
How do you pause the stream?
@chipweinberger

**Comment by chipweinberger** [comment]
just temporarily stop feeding

**Comment by gokturkDev** [comment]
So stop is pause, release is stop now?
 @chipweinberger

**Comment by chipweinberger** [comment]
`pause/stop` = don't feed more samples

`release` = full cleanup, same as before

**Comment by gokturkDev** [comment]
got it i think this much better as well thanks
