### ISSUE TITLE
real-time explained

### ISSUE THREAD

**Issue by jtkeyva** [chipweinberger/flutter_pcm_sound#6]
is the purpose of this to playback audio with low latency? someone was asking and i found soundpool. what's the difference?
thanks

**Comment by chipweinberger** [comment]
yes low latency.

never used soundpool

**Comment by chipweinberger** [comment]
`soundpool` is for playing audio files, i.e. mp3, m4a, etc. The audio files must be pre-generated and written to a file.

`flutter_pcm_sound` is for playing pcm audio. The audio can be generated in realtime.

**Comment by jtkeyva** [comment]
thanks
